backpack/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('userLogin.urls', namespace='userLogin')),
    url(r'', include('myBackpack.urls', namespace='myBackpack')),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

myBackpack/urls.py
from django.conf.urls import url

from myBackpack import views
from myBackpack import apiviews

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),

    url(r'^new/backpack/', views.NewBackpack.as_view(), name='create-backpack'),

    url(r'^new/note/(?P<backpack_id>\d+)/',
        views.NewNote.as_view(), name='create-note'),

    url(r'^list/own/backpacks/',
        views.ListMyBackpacks.as_view(), name='my-backpacks'),

    url(r'^list/backpack/(?P<backpack_id>\d+)/notes/',
        views.ListBackpackNotes.as_view(), name='my-notes'),

    url(r'^detail/note/(?P<note_id>\d+)/',
        views.DetailNote.as_view(), name='detail-note'),

    url(r'^delete/note/(?P<note_id>\d+)/',
        views.DeleteNote.as_view(), name='delete-note'),

    url(r'^delete/backpack/(?P<backpack_id>\d+)/',
        views.DeleteBackpack.as_view(), name='delete-backpack'),

    url(r'^edit/backpack/(?P<backpack_id>\d+)/',
        views.EditBackpack.as_view(), name='edit-backpack'),

    url(r'^edit/note/(?P<note_id>\d+)/',
        views.EditNote.as_view(), name='edit-note'),
]

urlpatterns += [
    url(r'api/detail/note/(?P<note_id>\d+)/',
        apiviews.APIDetailNote.as_view(), name='api-detail-note'),

    url(r'api/detail/backpack/(?P<backpack_id>\d+)/',
        apiviews.APIDetailBackpack.as_view(), name='api-detail-backpack'),

    url(r'api/list/backpack/(?P<backpack_id>\d+)/notes/',
        apiviews.APIListBackpackNotes.as_view(), name='api-list-backpack-notes'),

    url(r'api/create/note/$',
        apiviews.APICreateNote.as_view(), name='api-create-note'),

    url(r'api/create/backpack/$',
        apiviews.APICreateBackpack.as_view(), name='api-create-backpack'),

    url(r'api/delete/backpack/(?P<backpack_id>\d+)/$',
        apiviews.APIDeleteBackpack.as_view(), name='api-delete-backpack'),

    url(r'api/delete/note/(?P<note_id>\d+)/$',
        apiviews.APIDeleteNote.as_view(), name='api-delete-note'),
]

userLogin/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'login/', views.Login.as_view(), name='login'),
    url(r'logout/', views.Logout.as_view(), name='logout'),
    url(r'register/', views.Register.as_view(), name='register'),
]

myBackpack/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class BackUser(models.Model):
    userAttached = models.OneToOneField(User, verbose_name="Username")
    memberType = models.CharField("Membership", max_length=50)

    def __str__(self):
        return self.userAttached.username


class Backpack(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)

    creationDate = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=False)

    owner = models.ForeignKey(BackUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Notes(models.Model):
    backpack = models.ForeignKey(Backpack, on_delete=models.CASCADE)

    title = models.CharField(max_length=100)
    content = models.TextField()

    creationDate = models.DateTimeField(auto_now_add=True)

    public = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def short_description(self):
        if len(self.content) > 50:
            return "{}...".format(self.content[:50])
        else:
            return self.content


class Tags(models.Model):
    tag = models.CharField(max_length=20)
    notes = models.ManyToManyField(Notes)

    def __str__(self):
        return self.tag

myBackpack/forms.py
from django.forms import ModelForm
from django.forms import HiddenInput
from django.forms import IntegerField
from django.forms import BooleanField

from .models import Backpack
from .models import Notes


class BackpackForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BackpackForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            current_field = self.fields[field]

            if (current_field is not self.fields['public']):
                current_field.widget.attrs['class'] = "form-control"
                current_field.widget.attrs['placeholder'] = current_field.label

            elif current_field is self.fields['public']:
                current_field.widget.attrs['aria-label'] = "..."

    class Meta:
        model = Backpack
        fields = ['name', 'description', 'public', ]


class NotesForm(ModelForm):
    backpack = IntegerField(widget=HiddenInput, required=False)

    def clean_backpack(self):
        backpack_id = self.cleaned_data['backpack']

        print "backpack_id: %s" % backpack_id

        try:
            backpack_to_add_note = Backpack.objects.get(pk=backpack_id)
        except Backpack.DoesNotExist:
            backpack_to_add_note = None

        return backpack_to_add_note

    def __init__(self, *args, **kwargs):
        super(NotesForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            current_field = self.fields[field]

            if (current_field is not self.fields['backpack'] and
                    current_field is not self.fields['public']):

                current_field.widget.attrs['class'] = "form-control"
                current_field.widget.attrs['placeholder'] = self.fields[field].label

            elif current_field is BooleanField:
                current_field.widget.attrs['aria-label'] = "..."

    class Meta:
        model = Notes
        fields = ['backpack', 'title', 'content', 'public', ]

myBackpack/views.py
from django.urls import reverse_lazy

from django.http import HttpResponseRedirect

from django.forms import ModelChoiceField
from django.forms import HiddenInput

from django.views.generic import RedirectView
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.views.generic import UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin

from django.shortcuts import get_object_or_404

from myBackpack.models import Backpack
from myBackpack.models import BackUser
from myBackpack.models import Notes

from myBackpack.forms import BackpackForm
from myBackpack.forms import NotesForm


class Index(RedirectView):
    url = reverse_lazy('myBackpack:my-backpacks')


class NewBackpack(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('userLogin:login')
    model = Backpack
    form_class = BackpackForm

    template_name = "newBackpack.html"
    success_url = reverse_lazy('myBackpack:my-backpacks')

    def get_initial(self):
        self.initial = {'owner': self.request.user}

        return super(NewBackpack, self).get_initial()

    def form_valid(self, form):
        name = form.cleaned_data.get('name')
        description = form.cleaned_data.get('description')
        public = form.cleaned_data.get('public')

        user_back = BackUser.objects.get(userAttached=self.request.user)

        self.object = Backpack(owner=user_back, name=name, description=description, public=public)
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(NewBackpack, self).get_context_data(**kwargs)
        context['new_backpack'] = True

        return context


class NewNote(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('userLogin:login')
    model = Notes
    form_class = NotesForm

    template_name = "new_note.html"

    def get_initial(self):
        backpack_to_add_note = self.kwargs.get("backpack_id")
        self.initial = {'backpack': backpack_to_add_note}

        return super(NewNote, self).get_initial()

    def form_valid(self, form):
        back_user = BackUser.objects.get(userAttached=self.request.user)

        form_backpack = form.cleaned_data.get('backpack')
        user_backpacks = Backpack.objects.filter(owner=back_user)

        if form_backpack not in user_backpacks:

            form.add_error(None, "The note cannot be added to other user's backpack")

            form.data = form.data.copy()
            form.fields['backpack'] = ModelChoiceField(queryset=Backpack.objects.filter(owner=back_user))

            return super(NewNote, self).form_invalid(form)

        self.success_url = reverse_lazy('myBackpack:my-notes', kwargs={'backpack_id': form_backpack.pk})

        return super(NewNote, self).form_valid(form)


class ListBackpackNotes(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('userLogin:login')

    context_object_name = "notes"
    model = Notes

    template_name = "list_self_notes.html"

    def get_queryset(self):
        back_user = BackUser.objects.get(userAttached=self.request.user)

        backpack = get_object_or_404(Backpack, pk=self.kwargs.get("backpack_id"))
        user_backpacks = Backpack.objects.filter(owner=back_user)

        if backpack not in user_backpacks:
            self.raise_exception = True
            self.permission_denied_message = "You don't have the permissions required to see the specified backpack."

            return super(ListBackpackNotes, self).handle_no_permission()

        else:
            self.queryset = backpack.notes_set.all()

            return super(ListBackpackNotes, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super(ListBackpackNotes, self).get_context_data(**kwargs)

        backpack = Backpack.objects.get(pk=self.kwargs.get("backpack_id"))

        context['backpack'] = backpack

        return context


class ListMyBackpacks(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('userLogin:login')

    model = Backpack
    context_object_name = "backpacks"

    template_name = "listBackpacks.html"

    def get_queryset(self):
        userBackpack = BackUser.objects.get(userAttached=self.request.user)
        self.queryset = Backpack.objects.filter(owner=userBackpack)

        return super(ListMyBackpacks, self).get_queryset()


class DetailNote(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    login_url = reverse_lazy('userLogin:login')

    model = Notes
    context_object_name = "note"
    template_name = "notes_detail.html"
    pk_url_kwarg = "note_id"

    raise_exception = True

    def test_func(self):
        note = self.get_object(queryset=None)

        return (note.backpack.owner.userAttached == self.request.user or
                note.public)


class DeleteNote(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    login_url = reverse_lazy('userLogin:login')

    model = Notes
    template_name = "delete_note.html"

    pk_url_kwarg = "note_id"

    raise_exception = True

    def post(self, request, *args, **kwargs):
        note = self.get_object()
        self.success_url = reverse_lazy('myBackpack:my-notes', kwargs={'backpack_id': note.backpack.pk})

        return super(DeleteNote, self).post(request, *args, **kwargs)

    def test_func(self):
        note = self.get_object()
        note_owner = note.backpack.owner.userAttached

        return note_owner == self.request.user


class DeleteBackpack(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    login_url = reverse_lazy('userLogin:login')

    model = Backpack
    template_name = "delete_backpack.html"

    pk_url_kwarg = "backpack_id"
    success_url = reverse_lazy('myBackpack:my-backpacks')

    raise_exception = True

    def test_func(self):
        backpack = self.get_object()

        return backpack.owner.userAttached == self.request.user


class EditNote(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy('userLogin:login')

    model = Notes
    pk_url_kwarg = 'note_id'

    form_class = NotesForm

    template_name = 'edit_note.html'
    raise_exception = True

    def test_func(self):
        note = self.get_object()

        return note.backpack.owner.userAttached == self.request.user

    def get_form(self, form_class=None):
        form = super(EditNote, self).get_form(form_class=None)

        form.fields['backpack'].widget = HiddenInput()

        return form

    def get_success_url(self):
        note = self.get_object()

        self.success_url = reverse_lazy('myBackpack:my-notes', kwargs={'backpack_id': note.backpack.pk})

        return super(EditNote, self).get_success_url()

    def form_valid(self, form):
        form_backpack = form.cleaned_data['backpack']

        back_user = BackUser.objects.get(userAttached=self.request.user)

        if form_backpack in back_user.backpack_set.all():
            return super(EditNote, self).form_valid(form)
        else:
            form.add_error(None, "You don't have the permissions to save the no"
                           "te under another user backpack")

            note = self.get_object()

            form.data = form.data.copy()
            form.data['backpack'] = note.backpack.pk

            return super(EditNote, self).form_invalid(form)


class EditBackpack(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy('userLogin:login')

    model = Backpack
    pk_url_kwarg = 'backpack_id'

    form_class = BackpackForm

    template_name = 'edit_backpack.html'

    success_url = reverse_lazy('myBackpack:my-backpacks')
    raise_exception = True

    def test_func(self):
        backpack = self.get_object()

        return backpack.owner.userAttached == self.request.user

    def get_initial(self):
        username = self.request.user
        self.initial = {'owner': username}

        return super(EditBackpack, self).get_initial()

    def form_valid(self, form):
        form_user = form.cleaned_data['owner']

        current_back_user = BackUser.objects.get(userAttached=self.request.user)

        if form_user == current_back_user:
            return super(EditBackpack, self).form_valid(form)
        else:
            form.add_error(None, "The Backpack that is being edited does not corresponds to the user's backpacks")

            form.data = form.data.copy()
            form.data['owner'] = self.request.user

            return super(EditBackpack, self).form_invalid(form)

myBackpack/templates/delete_backpack.html
{% extends 'main.html' %}

{% block content %}
<div class="row">
  <div class="col-lg-2"></div>
  <div class="col-lg-8 text-center">
    <h3>Delete Backpack</h3>

    <form action="" method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete {{backpack.name}}?</p>
      <input type="submit" class="btn btn-danger text-center" value="Delete Backpack">
    </form>
  </div>
  <div class="col-lg-2"></div>
</div>
{% endblock %}

myBackpack/templates/delete_note.html
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Erase note">
</form>

myBackpack/templates/edit_backpack.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <h1>Edit backpack</h1>
      <form action="" method="post">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{hidden}}
        {% endfor %}

        {% for field in form.visible_fields %}
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
          {% if field is not form.public %}
            <label>
              {{ field.label_tag }}
            </label>
            {{ field }}
            <p class="help-block text-danger"></p>
          {% else %}
            <div class="input-group">
              <span class="input-group-addon">
                {{field}}
              </span>
              <input class="form-control" type="text" readonly="" placeholder="Make public?">
            </div>
          {% endif %}
          </div>
        </div>
        {% endfor %}

        <br>
        <div class="row">
          <div class="form-group col-xs-12">
            <button class="btn btn-default" type="submit">Save changes</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create new Backpack">
</form>

myBackpack/templates/edit_note.html
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save changes">
</form>

myBackpack/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
  <body>
    Welcome back, {{request.user}} 
  </body>
</html>

myBackpack/templates/listBackpacks.html
{% extends "main.html" %}

{% block content %}

<div class="row">
    <h1 class="text-center">List of saved backpacks</h1>
    <hr>
</div>

{% for backpack in backpacks %}
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <a href="{% url 'myBackpack:my-notes' backpack.pk %}">
            <h2>{{ backpack.name }}</h2>
        </a>
        <i>{{ backpack.description }}</i>

        {% if backpack.public %}
        <p><b>This backpack is public</b></p>
        {% else %}
        <br>
        {% endif %}

        <a class="pull-right" href="{% url 'myBackpack:delete-backpack' backpack.pk %}">Delete Backpack</a>
        <hr>
    </div>
    <div class="col-lg-2"></div>
</div>
{% endfor %}
{% endblock %}

myBackpack/templates/list_self_notes.html
{% extends 'main.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <h1 class="text-center">Notes saved in {{ backpack.name }}</h1>
        <p class="text-center">{{ backpack.description }}</p>
        <i><a href="{% url 'myBackpack:edit-backpack' backpack.pk %}">Edit Backpack</a></i>
        <i><a href="{% url 'myBackpack:create-note' backpack.pk %}" class="pull-right">New note</a></i>
        <hr>
    </div>
    <div class="col-lg-2"></div>
</div>

{% for note in notes %}
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <a href="{% url 'myBackpack:detail-note' note.pk %}">
            <h2>{{ note.title }}</h2>
        </a>

        <i>{{ note.short_description }}</i>

        {% if note.public %}
        <p><b>This note is public</b></p>
        {% endif %}

        <a href="{% url 'myBackpack:delete-note' note.pk %}" class="pull-right">Delete note</a>
        <hr>
    </div>
    <div class="col-lg-2"></div>
</div>
{% endfor %}
{% endblock %}

myBackpack/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>My Backpacks</title>

  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">

  {% block head %}
  {% endblock %}

</head>
  <body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">My Backpack</a>
            </div>

            <div id="navbar-collapse-1" class="collapse navbar-collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li {% if not new_backpack %}class="active"{% endif %}><a href="{% url 'myBackpack:my-backpacks' %}">My backpacks</a></li>
                    <li {% if new_backpack %}class="active"{% endif %}><a href="{% url 'myBackpack:create-backpack' %}">New backpack</a></li>
                </ul>
                {% endif %}

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="">Welcome back, {{ user }}</a></li>
                    <li><a href="{% url 'userLogin:logout' %}">Logout</a></li>
                    {% else %}
                    <li {% if login %}class="active"{% endif %}><a href="{% url 'userLogin:login' %}">Login</a></li>
                    <li {% if register %}class="active"{% endif %}><a href="{% url 'userLogin:register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static "js/jquery-3.1.0.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>

myBackpack/templates/newBackpack.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h1 class="text-center">Register a new backpack</h1>
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <form action="" method="post">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}
                {% if field is not form.public %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% else %}
                <div class="input-group">
                    <span class="input-group-addon">{{ field }}</span>
                    <input class="form-control" type="text" readonly="" placeholder="Make public?">
                </div>
                {% endif %}
                {% endfor %}
                <br>
                <button class="btn btn-default" type="submit">Create new backpack</button>
            </form>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>
{% endblock %}

myBackpack/templates/new_note.html
{% extends "main.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <h2>Add a new note</h2>
      <p>Please fill the form to add a new note to the selected backpack</p>

      <form action="" method="post">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            {% if field is not form.public %}
              <label>
                {{ field.label_tag }}
              </label>
              {{ field }}
              <p class="help-block text-danger"></p>
            {% else %}
            <div class="input-group">
              <span class="input-group-addon">
                {{field}}
              </span>
              <input class="form-control" type="text" readonly="" placeholder="Make public?">
            </div>
            {% endif %}
          </div>
        </div>
        {% endfor %}

        <br>
        <div class="row">
          <div class="form-group col-xs-12">
            <button class="btn btn-default" type="submit">Add new note</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

myBackpack/templates/notes_detail.html
{% extends 'main.html' %}

{% block content %}
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <h1 class="text-center">{{ note.title|upper }}</h1>
        <p class="text-center">Created by <i>{{note.backpack.owner.userAttached.username}}</i> on <i>{{ note.creationDate|date:"F d, o" }}</i></p>
        {% if note.public %}
        <i><p class="text-center">This note is public</p></i>
        {% endif %}
        <hr>
        <p>{{ note.content|title }}</p>
      </div>
    </div>
  </div>
</article>
{% endblock %}